[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Add this new redirect for your data
[[redirects]]
  from = "/data/maandamanoCheck.json"
  to = "/.netlify/functions/getData"
  status = 200